apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow Simple test
on:
  workflow_dispatch:
jobs:
  tekton:
    steps:
      - name: hello
        id: hello
        uses: docker://alpine:3
        shell: sh
        run: |
          echo "Hello, world! I'm $(whoami) on $(hostname)"
  remote:
    with:
      script: |
        echo "Hello world! I'm $(whoami) on $(hostname)"
      labels: self-hosted,my-label-3
    delegates: https://github.com/mluzcabrera/prod_test_edge_runners_v0.1/custom-job.yml
